kind: Service
apiVersion: v1
metadata:
  labels:
    app: zoo-headless
  name: zoo-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: zoo2888
    - name: zoo3888
      protocol: TCP
      port: 3888
      targetPort: 3888
    - name: zoo2181
      protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    app: zoo


---
apiVersion: v1
data:
  configuration.xsl: |
    <?xml version="1.0"?>
    <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="html"/>
    <xsl:template match="configuration">
    <html>
    <body>
    <table border="1">
    <tr>
     <td>name</td>
     <td>value</td>
     <td>description</td>
    </tr>
    <xsl:for-each select="property">
    <tr>
      <td><a name="{name}"><xsl:value-of select="name"/></a></td>
      <td><xsl:value-of select="value"/></td>
      <td><xsl:value-of select="description"/></td>
    </tr>
    </xsl:for-each>
    </table>
    </body>
    </html>
    </xsl:template>
    </xsl:stylesheet>
  log4j.properties: |
    zookeeper.root.logger=INFO, CONSOLE

    zookeeper.console.threshold=INFO

    zookeeper.log.dir=.
    zookeeper.log.file=zookeeper.log
    zookeeper.log.threshold=INFO
    zookeeper.log.maxfilesize=256MB
    zookeeper.log.maxbackupindex=20

    zookeeper.tracelog.dir=${zookeeper.log.dir}
    zookeeper.tracelog.file=zookeeper_trace.log

    log4j.rootLogger=${zookeeper.root.logger}

    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n

    log4j.appender.ROLLINGFILE=org.apache.log4j.RollingFileAppender
    log4j.appender.ROLLINGFILE.Threshold=${zookeeper.log.threshold}
    log4j.appender.ROLLINGFILE.File=${zookeeper.log.dir}/${zookeeper.log.file}
    log4j.appender.ROLLINGFILE.MaxFileSize=${zookeeper.log.maxfilesize}
    log4j.appender.ROLLINGFILE.MaxBackupIndex=${zookeeper.log.maxbackupindex}
    log4j.appender.ROLLINGFILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.ROLLINGFILE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n

    log4j.appender.TRACEFILE=org.apache.log4j.FileAppender
    log4j.appender.TRACEFILE.Threshold=TRACE
    log4j.appender.TRACEFILE.File=${zookeeper.tracelog.dir}/${zookeeper.tracelog.file}

    log4j.appender.TRACEFILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.TRACEFILE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L][%x] - %m%n
    zookeeper.auditlog.file=zookeeper_audit.log
    zookeeper.auditlog.threshold=INFO
    audit.logger=INFO, RFAAUDIT
    log4j.logger.org.apache.zookeeper.audit.Log4jAuditLogger=${audit.logger}
    log4j.additivity.org.apache.zookeeper.audit.Log4jAuditLogger=false
    log4j.appender.RFAAUDIT=org.apache.log4j.RollingFileAppender
    log4j.appender.RFAAUDIT.File=${zookeeper.log.dir}/${zookeeper.auditlog.file}
    log4j.appender.RFAAUDIT.layout=org.apache.log4j.PatternLayout
    log4j.appender.RFAAUDIT.layout.ConversionPattern=%d{ISO8601} %p %c{2}: %m%n
    log4j.appender.RFAAUDIT.Threshold=${zookeeper.auditlog.threshold}

    log4j.appender.RFAAUDIT.MaxFileSize=10MB
    log4j.appender.RFAAUDIT.MaxBackupIndex=10
  zoo.cfg: |
    tickTime=6000
    dataDir=/data
    clientPort=2181
    initLimit=5
    syncLimit=2
    server.1=zookeeper-cluster-0.zoo-headless:2888:3888
    server.2=zookeeper-cluster-1.zoo-headless:2888:3888
    server.3=zookeeper-cluster-2.zoo-headless:2888:3888
kind: ConfigMap
metadata:
  name: zoo-config
  namespace: default

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: zoo-conf
data:
  zoo.cfg: |
       tickTime=6000
       dataDir=/data
       clientPort=2181
       initLimit=5
       syncLimit=2
       server.1=zookeeper-cluster-0.zoo-headless:2888:3888
       server.2=zookeeper-cluster-1.zoo-headless:2888:3888
       server.3=zookeeper-cluster-2.zoo-headless:2888:3888


---

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: zookeeper-cluster
  labels:
    app: zoo
spec:
  selector:
    matchLabels:
      app: zoo
  serviceName: zoo-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: zoo
    spec:
      initContainers:
        - name: init-zookeeper
          image: bash:5
          imagePullPolicy: IfNotPresent
          command:
              - bash
              - "-c"
              - |
                set -ex
                [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
                ordinal=${BASH_REMATCH[1]}
                echo $((1 + $ordinal)) >> /data/myid
                cp /etc/zooconf/* /emptydir/
                #cp /conf/* /emptydir/
          volumeMounts:
              - name: zoo-data
                mountPath: /data
              - name: config
                mountPath: /etc/zooconf
              - name: configdir
                mountPath: /emptydir
      containers:
        - name: zookeeper
          image: zookeeper:3.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: client-port
              containerPort: 2181
            - name: cluster-port
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          volumeMounts:
            - name: zoo-data
              mountPath: /data
            - name: configdir #docker-entrypoint.sh
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: zoo-config
        - name: configdir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: zoo-data
      spec:
        storageClassName: hostpath #docker desktop default storageClass
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
